### ISSUE TITLE
有exe可执行文件吗

### ISSUE THREAD

**Issue by July-chat** [zlz-cn/bow_feat#1]
你好可不可以给我发下这个文件的exe执行文件

**Comment by zlz-cn** [comment]
发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: July-chat<mailto:notifications@github.com>
发送时间: 2020年5月29日 13:33
收件人: zlz-cn/bow_feat<mailto:bow_feat@noreply.github.com>
抄送: Subscribed<mailto:subscribed@noreply.github.com>
主题: [zlz-cn/bow_feat] 有exe可执行文件吗 (#1)


你好可不可以给我发下这个文件的exe执行文件

―

**Comment by zlz-cn** [comment]
已发送

**Comment by July-chat** [comment]
你好发送在哪里了？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zlz-cn"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月1日(星期一) 晚上6:03
收件人:&nbsp;"zlz-cn/bow_feat"<bow_feat@noreply.github.com&gt;;
抄送:&nbsp;"409594339"<409594339@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zlz-cn/bow_feat] 有exe可执行文件吗 (#1)





 
已发送
